### PR TITLE
Update st_stuff.c

### PR DESCRIPTION
**Pull request by dirsors**
Fix the following:
- Doom v1.9 doesn't allow cheats in nightmare mode!
- clev cheat
- Ouch Face bug.

### CODE REVIEW

**Review by cosmito — APPROVED** [review]

**Comment by Wolf3s** [comment]
Are you back?

**Comment by cosmito** [comment]
hi, not really : | Just merged a pull-request from dirsors.

**Comment by Wolf3s** [comment]
> hi, not really : | Just merged a pull-request from dirsors.

Oh, that's kind of sad.
either way did you check out the forks sections?

**Comment by cosmito** [comment]
I think in the past I did checked though not recently. I find it great people are moving this forward. You have one of the forks, right?

**Comment by Wolf3s** [comment]
> I think in the past I did checked though not recently. I find it great people are moving this forward. You have one of the forks, right?

Yeah i'm the one, who tried to continued with this

**Comment by Wolf3s** [comment]
Here is a demo video: https://youtu.be/J0Lf_rGiFVk

**Pull request merged**
